package com.db;

import com.core.Context;
import com.core.Logger;
import com.core.WbException;
import com.model.*;

import java.sql.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.sql.rowset.serial.SerialBlob;

/**
 * DatabaseConnector is the class responsible for holding the connection to the MySQL database,
 * and provides an interface to interact with the MySQL database.
 * @author Stephen Davidson
 * @author Jared Gorton
 */
public class DatabaseConnector {
	private String host;
	private String username;
	private String password;
	private boolean isLocal;

	private Connection c;

	/**
	 * Class constructor.
	 */
	public DatabaseConnector(String host, String username, String password, boolean isLocal) {
		this.host = host;
		this.username = username;
		this.password = (isLocal) ? null : password;
		this.isLocal = isLocal;
	}

	/**
	 * startConnection begins a new connection the MySQL database, and initializes the database
	 * tables. The connection should exist for as long as the server is up.
	 */
	public void startConnection() throws WbException {
		try {
			Class.forName("com.mysql.jdbc.Driver");
			c = DriverManager.getConnection(this.host, this.username, this.password);
		} catch (Exception e) {
			throw new WbException(WbException.DB_START_CONNECTION, e);
		}
		if (c != null) {
			Logger.log.info("Connected to MySQL database.");
			initTables(this.isLocal);
		}
	}

	/**
	 * endConnection closes the connection to the MySQL database.
	 */
	public void endConnection() throws WbException {
		try {
			c.close();
			Logger.log.info("Disconnected from MySQL database.");
		} catch (Exception e) {
			throw new WbException(WbException.DB_END_CONNECTION, e);
		}
	}

	/**
	 * initTables creates all the database tables, if needed. On local run, initTables
	 * first drops all the existing tables in the MySQL database.
	 */
	private void initTables(boolean isLocal) throws WbException {
		if (isLocal) {
			try {
				Logger.log.info("Clearing old database tables for local run.");
				Statement stmt = c.createStatement();
				stmt.addBatch(MySQL.REMOVE_WHITEBOARDS_TABLE);
				stmt.addBatch(MySQL.REMOVE_IMAGES_TABLE);
				stmt.addBatch(MySQL.REMOVE_EDITS_TABLE);
				stmt.addBatch(MySQL.REMOVE_POINTS_TABLE);
				stmt.addBatch(MySQL.REMOVE_USERS_TABLE);
				stmt.addBatch(MySQL.REMOVE_MESSAGES_TABLE);
				stmt.executeBatch();
				stmt.close();
			} catch (Exception e) {
				throw new WbException(WbException.DB_CLEAR_TABLES, e);
			}
		}

		try {
			Logger.log.info("Creating database tables.");
			Statement stmt = c.createStatement();
			stmt.addBatch(MySQL.CREATE_WHITEBOARDS_TABLE);
			stmt.addBatch(MySQL.CREATE_IMAGES_TABLE);
			stmt.addBatch(MySQL.CREATE_EDITS_TABLE);
			stmt.addBatch(MySQL.CREATE_POINTS_TABLE);
			stmt.addBatch(MySQL.CREATE_USERS_TABLE);
			stmt.addBatch(MySQL.CREATE_MESSAGES_TABLE);
			stmt.executeBatch();
			stmt.close();
		} catch (Exception e) {
			throw new WbException(WbException.DB_INIT_TABLES, e);
		}
	}

	/**
	 * addWhiteboard inserts a new Whiteboard into the Whiteboards table.
	 * @param wb model Whiteboard to be stored.
	 */
	public void addWhiteboard(Whiteboard wb) throws WbException {
		Logger.log.info("Adding a Whiteboard.");
		try {
			PreparedStatement stmt = c.prepareStatement(MySQL.ADD_WHITEBOARD);
			stmt.setString(1, wb.getWbID());
			stmt.setString(2, wb.getName());
			stmt.executeUpdate();
			stmt.close();
		} catch (Exception e) {
			throw new WbException(WbException.DB_ADD_WB, e);
		}
	}

	/**
	 * removeWhiteboard deletes a specified Whiteboard from the Whiteboards table.
	 * @param wb model Whiteboard to be removed.
	 */
	public void removeWhiteboard(Whiteboard wb) throws WbException {
		Logger.log.info("Removing a Whiteboard.");
		try {
			PreparedStatement stmt = c.prepareStatement(MySQL.REMOVE_WHITEBOARD);
			stmt.setString(1, wb.getWbID());
			stmt.executeUpdate();
			stmt.close();
		} catch (Exception e) {
			throw new WbException(WbException.DB_REMOVE_WB, e);
		}
	}

	/**
	 * renameWhiteboard sets the name field of a specified Whiteboard to the provided new name.
	 * @param wbID uuid belonging to the Whiteboard to be renamed.
	 * @param newName the new name that the Whiteboard will be renamed to.
	 */
	public void renameWhiteboard(String wbID, String newName) throws WbException {
		Logger.log.info("Renaming a Whiteboard.");
		try {
			PreparedStatement stmt = c.prepareStatement(MySQL.RENAME_WHITEBOARD);
			stmt.setString(1, newName);
			stmt.setString(2, wbID);
			stmt.executeUpdate();
			stmt.close();
		} catch (Exception e) {
			throw new WbException(WbException.DB_RENAME_WB, e);
		}
	}

	/**
	* addImage inserts a new Image into the Images table.
	* @param img model Image to be stored.
	* @return the image that was passed in, now with the autogenerated image id.
	*/
	public Image addImage(Image img) throws WbException {
		Logger.log.info("Adding an Image.");
		try {
			PreparedStatement stmt = c.prepareStatement(MySQL.ADD_IMAGE, Statement.RETURN_GENERATED_KEYS);
			stmt.setString(1, img.getWbID());
			stmt.setString(2, img.getFilename());
			stmt.setTimestamp(4, new Timestamp(img.getTimestamp().getTime()));
			if (img.getBytes() != null && img.getBytes().length > 0)
				stmt.setBlob(3, (Blob) new SerialBlob(img.getBytes()));
			else
				stmt.setNull(3, java.sql.Types.BLOB);
			stmt.executeUpdate();
			ResultSet rs = stmt.getGeneratedKeys();
			rs.next();
			img.setImgID(rs.getInt(1));
			stmt.close();
		} catch (Exception e) {
			throw new WbException(WbException.DB_ADD_IMG, e);
		}

		return img;
	}

	/**
	* addEdit inserts a new Edit into the Edits table.
	* @param edit model Edit to be stored.
	* @return the edit that was passed in, now with the autogenerated edit id.
	*/
	public Edit addEdit(Edit edit) throws WbException {
		Logger.log.info("Adding an Edit.");
		try {
			PreparedStatement stmt = c.prepareStatement(MySQL.ADD_EDIT);
			stmt.setString(1, edit.getWbID());
			stmt.setString(2, edit.getUsername());
			stmt.setInt(3, edit.getColor());
			stmt.setInt(4, edit.getBrushSize());
			stmt.setTimestamp(5, new Timestamp(edit.getTimestamp().getTime()));
			stmt.executeUpdate();
			ResultSet rs = stmt.getGeneratedKeys();
			rs.next();
			edit.setEditID(rs.getInt(1));
			stmt.close();
		} catch (Exception e) {
			e.printStackTrace();
			throw new WbException(WbException.DB_ADD_EDIT, e);
		}

		return edit;
	}

	/**
	 * removeEdit deletes a specified Edit from the Edits table.
	 * @param edit model Edit to be removed.
	 */
	public void removeEdit(Edit edit) throws WbException {
		Logger.log.info("Removing an Edit.");
		try {
			PreparedStatement stmt = c.prepareStatement(MySQL.REMOVE_EDIT);
			stmt.setInt(1, edit.getEditID());
			stmt.executeUpdate();
			stmt.close();
		} catch (Exception e) {
			throw new WbException(WbException.DB_REMOVE_EDIT, e);
		}
	}

	/**
	* addPoints inserts a list of Points into the Points table.
	* @param points list of model Points to be stored.
	*/
	public void addPoints(List<Point> points) throws WbException {
		Logger.log.info("Adding Points.");

		for (Point p : points) {
			try {
				PreparedStatement stmt = c.prepareStatement(MySQL.ADD_POINT);
				stmt.setInt(1, p.getEditID());
				stmt.setInt(2, p.getXCoord());
				stmt.setInt(3, p.getYCoord());
				stmt.executeUpdate();
				stmt.close();
			} catch (Exception e) {
				throw new WbException(WbException.DB_ADD_POINTS, e);
			}
		}
	}

	/**
	 * removePoints deletes all the points with the provided edit id from the Points table.
	 * @param editID edit id for which all points will be removed.
	 */
	public void removePoints(int editID) throws WbException {
		Logger.log.info("Removing Points.");
		try {
			PreparedStatement stmt = c.prepareStatement(MySQL.REMOVE_POINTS);
			stmt.setInt(1, editID);
			stmt.executeUpdate();
			stmt.close();
		} catch (Exception e) {
			throw new WbException(WbException.DB_REMOVE_POINTS, e);
		}
	}

	/**
	* addUser inserts a new User into the Users table.
	* @param user model User to be stored.
	*/
	public void addUser(User user) throws WbException {
		Logger.log.info("Adding a User.");
		try {
			PreparedStatement stmt = c.prepareStatement(MySQL.ADD_USER);
			stmt.setString(1, user.getWbID());
			stmt.setString(2, user.getUsername());
			stmt.setInt(3, user.getMode().getValue());
			stmt.executeUpdate();
			stmt.close();
		} catch (Exception e) {
			throw new WbException(WbException.DB_ADD_USER, e);
		}
	}

	/**
	 * renameUser sets the name field of a specified User to the provided new name.
	 * @param user model User to be renamed.
	 * @param newName the new name that the User will be renamed to.
	 */
	public void renameUser(User user, String newName) throws WbException {
		Logger.log.info("Renaming a User.");
		try {
			PreparedStatement stmt = c.prepareStatement(MySQL.REMOVE_USER);
			stmt.setString(1, user.getWbID());
			stmt.setString(2, user.getUsername());
			stmt.executeUpdate();
			stmt.close();
		} catch (Exception e) {
			throw new WbException(WbException.DB_RENAME_USER, e);
		}
	}

	/**
	 * setUserMode sets the mode field of a specified User to the provided mode.
	 * @param user model User whose mode will be set.
	 * @param mode the mode that the User will be set to.
	 */
	public void setUserMode(User user, Mode mode) throws WbException {
		Logger.log.info("Setting User Mode.");
		try {
			PreparedStatement stmt = c.prepareStatement(MySQL.SET_USER_MODE);
			stmt.setInt(1, user.getMode().getValue());
			stmt.setString(2, user.getWbID());
			stmt.setString(3, user.getUsername());
			stmt.executeUpdate();
			stmt.close();
		} catch (Exception e) {
			throw new WbException(WbException.DB_SET_USER_MODE, e);
		}
	}

	/**
	 * removeUser deletes a specified User from the Users table.
	 * @param user model User to be removed.
	 */
	public void removeUser(User user) throws WbException {
		Logger.log.info("Removing a User.");
		try {
			PreparedStatement stmt = c.prepareStatement(MySQL.REMOVE_USER);
			stmt.setString(1, user.getWbID());
			stmt.setString(2, user.getUsername());
			stmt.executeUpdate();
			stmt.close();
		} catch (Exception e) {
			throw new WbException(WbException.DB_REMOVE_USER, e);
		}
	}

	/**
	* addMessage inserts a new Message into the Messages table.
	* @param msg model Message to be stored.
	* @return the message that was passed in, now with the autogenerated message id.
	*/
	public Message addMessage(Message msg) throws WbException {
		Logger.log.info("Adding a Message.");
		try {
			PreparedStatement stmt = c.prepareStatement(MySQL.ADD_MESSAGE);
			stmt.setString(1, msg.getWbID());
			stmt.setString(2, msg.getUsername());
			stmt.setString(3, msg.getMessage());
			stmt.setTimestamp(4, new Timestamp(msg.getTimestamp().getTime()));
			stmt.executeUpdate();
			ResultSet rs = stmt.getGeneratedKeys();
			rs.next();
			msg.setMessageID(rs.getInt(1));
			stmt.close();
		} catch (Exception e) {
			e.printStackTrace();
			throw new WbException(WbException.DB_ADD_MESSAGE, e);
		}

		return msg;
	}

	/**
	 * removeMessage deletes a specified Message from the Messages table.
	 * @param msg model Message to be removed.
	 */
	public void removeMessage(Message msg) throws WbException {
		Logger.log.info("Removing a Message.");
		try {
			PreparedStatement stmt = c.prepareStatement(MySQL.REMOVE_MESSAGE);
			stmt.setInt(1, msg.getMessageID());
			stmt.executeUpdate();
			stmt.close();
		} catch (Exception e) {
			throw new WbException(WbException.DB_REMOVE_MESSAGE, e);
		}
	}

	/**
	 * @param wbID uuid of the requested Whiteboard.
	 * @return the Whiteboard corresponding to the specified id.
	 */
	public Whiteboard getWhiteboard(String wbID) throws WbException {
		Logger.log.info("Querying for a Whiteboard.");

		String name = null;

		boolean found = false;
		try {
			PreparedStatement stmt = c.prepareStatement(MySQL.GET_WHITEBOARD);
			stmt.setString(1, wbID);

			ResultSet rs = stmt.executeQuery();
			if (rs.next()) {
				name = rs.getString("Name");
				found = true;
			}

			rs.close();
			stmt.close();
		} catch (Exception e) {
			throw new WbException(WbException.DB_GET_WB, e);
		}
		if (!found)
			throw new WbException(WbException.WHITEBOARD_DNE);

		// Images and edits should be null
		Whiteboard wb = new Whiteboard(wbID, name, null, null);
		return wb;
	}

	/**
	 * @param wbID uuid of the requested Whiteboard.
	 * @return the most recent Image of a Whiteboard corresponding to the specified id.
	 */
	public Image getImage(String wbID) throws WbException {
		Logger.log.info("Querying for an Image.");

		int imgID = -1;
		String filename = null;
		byte[] bytes = null;
		Date timestamp = null;

		boolean found = false;
		try {
			PreparedStatement stmt = c.prepareStatement(MySQL.GET_IMAGE);
			stmt.setString(1, wbID);

			ResultSet rs = stmt.executeQuery();
			if (rs.next()) {
				imgID = rs.getInt("ImageID");
				filename = rs.getString("Filename");
				timestamp = rs.getTimestamp("Timestamp");

				Blob blob = rs.getBlob("Bytes");
				if (blob != null)
					bytes = blob.getBytes(1, (int) blob.length());
				found = true;
			}
			rs.close();
			stmt.close();
		} catch (Exception e) {
			throw new WbException(WbException.DB_GET_IMG, e);
		}

		return new Image(imgID, wbID, filename, bytes, timestamp);
	}

	/**
	 * @param wbID uuid of the requested Whiteboard.
	 * @return all the Images on the Whiteboard corresponding to the specified id.
	 */
	public List<Image> getImages(String wbID) throws WbException {
		ArrayList<Image> images = new ArrayList<Image>();

		int imgID = -1;
		String filename = null;
		byte[] bytes = null;
		Date timestamp = null;

		try {
			PreparedStatement stmt = c.prepareStatement(MySQL.GET_IMAGES);
			stmt.setString(1, wbID);

			ResultSet rs = stmt.executeQuery();
			while (rs.next()) {
				imgID = rs.getInt("ImageID");
				filename = rs.getString("Filename");
				timestamp = rs.getTimestamp("Timestamp");

				Blob blob = rs.getBlob("Bytes");
				// casted to an int from a long (problem when posting massive pictures?? over 4.2Gb i think)
				if (blob != null)
					bytes = blob.getBytes(1, (int) blob.length());

				images.add(new Image(imgID, wbID, filename, bytes, timestamp));
				bytes = null;
			}
			rs.close();
			stmt.close();
		} catch (Exception e) {
			throw new WbException(WbException.DB_GET_IMGS, e);
		}

		return images;
	}

	/**
	 * @param wbID uuid of the requested Whiteboard.
	 * @return all the Edits on the Whiteboard corresponding to the specified id.
	 */
	public List<Edit> getEdits(String wbID) throws WbException {
		ArrayList<Edit> edits = new ArrayList<Edit>();

		// WhiteboardID, Username, Color, BrushSize, Timestamp
		String username = null;
		int color = -1, brushsize = -1, editID = -1;
		Date timestamp = null;

		try {
			PreparedStatement stmt = c.prepareStatement(MySQL.GET_EDITS);
			stmt.setString(1, wbID);

			ResultSet rs = stmt.executeQuery();
			while (rs.next()) {
				editID = rs.getInt("EditID");
				username = rs.getString("Username");
				color = rs.getInt("Color");
				brushsize = rs.getInt("BrushSize");
				timestamp = rs.getTimestamp("Timestamp");

				// TODO: points field is using null value
				edits.add(new Edit(editID, wbID, username, color, brushsize, null));
			}
			rs.close();
			stmt.close();
		} catch (Exception e) {
			throw new WbException(WbException.DB_GET_EDITS, e);
		}

		return edits;
	}

	/**
	 * @param editID id of the requested Edit.
	 * @return all the Points on the Edit corresponding to the specified id.
	 */
	public List<Point> getPoints(int editID) throws WbException {
		Logger.log.info("Querying for Points.");
		ArrayList<Point> points = new ArrayList<Point>();
		try {
			PreparedStatement stmt = c.prepareStatement(MySQL.GET_POINTS);
			stmt.setInt(1, editID);

			ResultSet rs = stmt.executeQuery();
			while (rs.next()) {
				Point p = new Point(rs.getInt("EditID"), rs.getInt("X"), rs.getInt("Y"));
				points.add(p);
			}
		} catch (Exception e) {
			throw new WbException(WbException.DB_GET_POINTS, e);
		}

		return points;
	}

	/**
	 * @param wbID uuid of the requested Whiteboard.
	 * @param username name of the requested User.
	 * @return  User with the provided username and Whiteboard id.
	 */
	public User getUser(String wbID, String username) throws WbException {
		int modeNum = -1;

		boolean found = false;
		try {
			PreparedStatement stmt = c.prepareStatement(MySQL.GET_USER);
			stmt.setString(1, wbID);
			stmt.setString(2, username);

			ResultSet rs = stmt.executeQuery();
			if (rs.next()) {
				modeNum = rs.getInt("Mode");
				// TODO: validate values for color, brushsize, etc.
				found = true;
			}
		} catch (Exception e) {
			throw new WbException(WbException.DB_GET_USER, e);
		}

		if (!found)
			throw new WbException(WbException.USER_DNE);

		if (modeNum == Mode.HOST.getValue())
			return new User(wbID, username, Mode.HOST);
		else if (modeNum == Mode.COLLABORATOR.getValue())
			return new User(wbID, username, Mode.COLLABORATOR);
		else if (modeNum == Mode.VIEWER.getValue())
			return new User(wbID, username, Mode.VIEWER);
		else
			throw new WbException(WbException.DB_INVALID_MODE);
	}

	/**
	 * @param wbID uuid of the requested Whiteboard.
	 * @return  set of all Users with the provided username and Whiteboard id.
	 */
	public Set<User> getUsers(String wbID) throws WbException {
		HashSet<User> users = new HashSet<User>();

		String username = null;
		int modeNum = -1;

		try {
			PreparedStatement stmt = c.prepareStatement(MySQL.GET_USERS);
			stmt.setString(1, wbID);

			ResultSet rs = stmt.executeQuery();
			while (rs.next()) {
				username = rs.getString("Username");
				modeNum = rs.getInt("Mode");

				switch (modeNum) {
				case 0:
					users.add(new User(wbID, username, Mode.HOST));
					break;
				case 1:
					users.add(new User(wbID, username, Mode.COLLABORATOR));
					break;
				case 2:
					users.add(new User(wbID, username, Mode.VIEWER));
					break;
				default:
					throw new WbException(WbException.DB_INVALID_MODE);
				}
			}
		} catch (Exception e) {
			throw new WbException(WbException.DB_GET_USERS, e);
		}

		return users;
	}
}